### ISSUE TITLE
Enums which use allow_alias result in compile errors.

### ISSUE THREAD

**Issue by Blei** [stepancheg/rust-protobuf#108]
Cf. example and documentation in https://developers.google.com/protocol-buffers/docs/proto#enum

Proto enums are always translated as rust enums, which is not possible if multiple enum values alias the same integer value.

**Comment by stepancheg** [comment]
Partially fixed in d6e80593f38ce47dfa0c4912a3558fa33ee06143: non-unique enums are ignored. At least generated code can be compiled.

**Comment by stepancheg** [comment]
`allow_alias` option is implemented. However, there are open issues and open questions.

Given the definition:

```
enum EnumWithAlias {
    option allow_alias = true;
    A = 10;
    B = 20;
    A_AGAIN = 10;
}
```

#### Should `A == A_AGAIN` in terms of rust `Eq` trait?

Java version of protobuf does not override `equal` for enum, and in C++ enum is just int, so enums with same values are "equal". Currently `Eq` is implemented, and `A != A_AGAIN`. I have no preference at the moment.

#### Should a message with `enum` field set to `A` be equal to another message with the same field set to `A_AGAIN`?

I think, answer is yes (because both message gets serialized to the same byte sequence), and this is to be implemented.

#### How `enum` should be stored in the message `struct`? Currently it is stored as rust `enum`, and I think it should be changed to be stored as `i32`.

I think it is important for future compatibility of protocol. Currently unknown `enum` value in the stream results in parse failure.

The idea of protobuf is to be forward and backward compatible, thus unknown `enum` values (that could be added in the newer version of proto) should be preserved in parsed messages. So `enum` should be stored as `i32`.

#### If `enum` is stored as `i32`, what should `get_my_enum(&self) -> MyEnum` return for unknown enum values?

Java version of protobuf returns "default" enum value, which seems to be clearly incorrect to be. I think it is safer to panic.

**Comment by plietar** [comment]
[In protobuf3](https://developers.google.com/protocol-buffers/docs/reference/java-generated#enum), all Java enums have a ``UNRECOGNIZED`` value which is used as a fallback.

I think `get_my_enum` should return `Option<MyEnum>`, but that would break compatibility. I don't know what your policy is for this, but as an alternative, keep `get_my_enum` and panic if unknown, and add `get_maybe_my_enum`. However panicking there is probably not 

Otherwise, it could be done like in Java with a new value. However, this breaks compatibility as well as it can cause a non exhaustive match.

**Comment by stepancheg** [comment]
This is probably fixed already. Please reopen if the issue still exists.
