### ISSUE TITLE
Print/parse JSON

### ISSUE THREAD

**Issue by CoDEmanX** [stepancheg/rust-protobuf#142]
Spec: https://developers.google.com/protocol-buffers/docs/proto3#json

- [x] Basic types formatting
- [x] Map field
- [x] Well-known types
- [ ] Well-known types: `Any`
- [x] Well-known types: `Timestamp`
- [x] Printer/parser options
- [x] Printer option: Emit fields with default values
- [x] Printer option: Emit fields with default values, but oneof fields should still be printed once
- [x] Printer option: Emit fields with default values, but without messages
- [x] Parser option: Ignore unknown fields
- [x] Printer option: Use proto field name instead of lowerCamelCase name
- [x] Printer option: Emit enum values as integers instead of strings
- [x] Interop test against Google implementation
- [x] Interop test against Google implementation: well-known types

**Comment by xitep** [comment]
isn't formatting data as json better handled with something like `serde_json`?

**Comment by stepancheg** [comment]
@CoDEmanX Actually, binary protobuf is quite portable. It is designed for that, and encoding is [well specified](https://developers.google.com/protocol-buffers/docs/encoding?hl=en).

Protobuf encoding as JSON is needed to be implemented one day. It is also [well specified](https://developers.google.com/protocol-buffers/docs/proto3?hl=en#json), but it is not a priority, because encoding as JSON is not a primary goal of protobuf.

**Comment by CoDEmanX** [comment]
I'm not concerned about portability actually, I'm looking for a way to make protobuf human-readable. Debug printing is human-readable, except that it lacks line breaks (maybe just on Windows?), and binary data is oddly encoded, but I need it encoded as true binary data. Because I have no Rust knowledge, JSON would be the most straightforward solution, because it would be human-readable and even a browser could decode the binary bits.

I guess I could write protobuf messages to file and read them back in with e.g. Node.js and try to convert them to JSON there...

**Comment by stepancheg** [comment]
@CoDEmanX Note, pretty-printed serialization has been implemented recently. See d3b5647c16e78d2f5f81263646a4ec6f0c239fb9.

**Comment by wilg** [comment]
I'm very new to Rust so I can't necessarily help with this for a while, but having a canonical JSON format that can be both serialized and deserialized is a very useful feature because it lets you use the Protobuf toolchain and generated code with a robust JSON wire format or have human editable config files that are strongly typed and easily read via protobuf (which is one of my use cases).

**Comment by stepancheg** [comment]
@wilg JSON parser and formatter is work in progress, e. g. 4d4c6200fb77be1cf6e63b1ffd7af66836eae380.

Help is appreciated by the way.

Also, protobuf supports own text format, which is not JSON, and it should work now already.

**Comment by stepancheg** [comment]
Done except for the special handling of `Any` type.

`Any` is not implemented well in rust-protobuf (i. e. type registry is not implemented), so handling of `Any` is postponed.

**Comment by Ubehebe** [comment]
@stepancheg Can you publish a version of this crate that exports the `json` module? IIUC, it's on [master](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf/src/lib.rs#L55) but not the [latest release](https://github.com/stepancheg/rust-protobuf/blob/v2.2/protobuf/src/lib.rs) (2.2).

**Comment by aaronshim** [comment]
Hi, just a question: Is there a reason why this functionality (which was backported for v2.9 according to https://docs.rs/protobuf/2.9.0/protobuf/json/index.html) was removed from the v2.10 branch? Thank you!

**Comment by stepancheg** [comment]
@aaronshim it broke backwards compatibility with generated code, unfortunately.

I wanted to implement it backwards-compatible way, but that's a significant amount of work.

**Comment by stepancheg** [comment]
Version 2.9.0 is yanked BTW
