### ISSUE TITLE
Repeated should implement From et. al

### ISSUE THREAD

**Issue by m4b** [stepancheg/rust-protobuf#263]
Repeated is just a thin wrapper over vec. Instead of exposing just method, should implement from. 

This way people can call `into()` and not worry about importing the crate just to call `from_vec`

Since it can’t fail this seems even more appealing. 

Usecase: I only use protobuf as client. Importing protobuf crate just to call from_vec seems unnecessary.

**Comment by stepancheg** [comment]
Note that there are few functions implemented in #236, version is not released yet.

If more functions need to be added, PR is welcome.

Also, rust-protobuf codegen should have an option to generate fields of `Vec` type fields instead of `RepeatedField`. `RepeatedField` is an optimization, and it's not always needed.

**Comment by stepancheg** [comment]
Please reopen if this issue is still relevant.
