### ISSUE TITLE
UnexpectedWireType error

### ISSUE THREAD

**Issue by ccakes** [stepancheg/rust-protobuf#293]
I'm having an issue decoding a specific message however if I use [pq](https://github.com/sevagh/pq) which also uses this library, it works fine.

[Example project](https://github.com/ccakes/rust-proto-example)

That panics at runtime however pq decodes the binary data fine.

```bash
protoc -o ~/.pq/ethernet.fdset proto.proto
pq --msgtype cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ethernet_controller_driver_bag_v2_type < content.bin
```

pq is using this library, albeit an older version. I tried with 1.4 as well in case something changed since then but no luck.

Any ideas?

**Comment by stepancheg** [comment]
This command also reports no errors:

```
protoc --decode cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ethernet_controller_driver_bag_v2_type proto.proto < content.bin
```

**Comment by stepancheg** [comment]
OK, I know what's the issue.

A `.proto` file was changed in a backward-incompatible way, which is against protobuf recommendations.

Executing command above:

```
protoc --decode cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ethernet_controller_driver_bag_v2_type proto.proto < content.bin
```

Display this part:

```
  previous_alarms { ... }
  12 { ... }
```

From the `.proto` file:

```
    eth_ctrlr_alarms previous_alarms = 9;
...
    uint32 laser_squelch_enabled = 12;
```

Which means that field 12 in the proto file is `uint32` and rust-protobuf correctly reports unexpected wire type length-delimited (which is length delimited according to protoc output). Because of binary files does not match schema in `proto.proto`.

As far as I can see, Google protobuf quietly puts this field into unknown fields instead of reporting an error because the generated code for protobuf-C++ is slightly different (rust-protobuf [should do the same](https://github.com/stepancheg/rust-protobuf/issues/277), but for performance, not because rust-protobuf is incorrect).

What rust-protobuf could do better is provide more detailed diagnostics of failure, e. g. field name or number where parsing error happened.

**Comment by ccakes** [comment]
Thanks for the help troubleshooting! Sorry for the delay, I thought I'd replied and closed this one already

**Comment by matiasinsaurralde** [comment]
I'm getting this same error, still debugging!
