### ISSUE TITLE
ProtobufEnumOrUnknown design.

### ISSUE THREAD

**Issue by hicqu** [stepancheg/rust-protobuf#303]
I send a PR #302 to close #233. However, that's just a basic implement. We can discuss details and track it here.
Now the design is:

* Rename `ProtobufEnum` to `ProtoEnum`, and use `ProtobufEnum` as a struct.
  `struct<E: ProtoEnum> ProtobufEnum<E> { ... }`
  generated code:
  ```
  color: ProtobufEnum<Color>; // for protobuf3 signular enums
  color: Option<ProtobufEnum<Color>>; // for protobuf2 singular enums
  colors: Vec<ProtobufEnum<Color>>; // for repeated enums
  ```
  It's because I think `ProtobufEnumOrUnknown` is too long. But I can easily switch to it if you prefer.

* Implement `ProtobufValue` for both `E: ProtoEnum` and `ProtobufEnum<E>`.
  I believe implement the trait for one of them is enough. However I don't know for which one is better.

* `ProtobufEnum` has these methods to access:
  ```
  fn value(&self) -> i32;
  fn from_i32(&self) -> Self; // Not `Option<Self>`, different from `ProtoEnum`.
  fn result(self) -> Result<E, i32>; // Unknown values are stored in Err.
  fn unwrap() -> E;
  fn from_enum(e: E) -> Self; 
  ```
  Some old code will need to call `unwrap` or something similar for the change.

* Other relative API for read/write `Enum`s from/to stream is changed.

Is it OK? Please review it. @stepancheg .

**Comment by stepancheg** [comment]
> Rename ProtobufEnum to ProtoEnum, and use ProtobufEnum as a struct

I also dislike too lengthy name `ProtobufEnumOrUnknown`.

However `ProtobufEnum` vs `ProtoEnum` will be confusing.

What about `ProtobufEnumHolder` instead of `ProtobufEnumOrUnknown`?

Or `ProtobufEnum` for struct and `ProtobufEnumTrait` for a trait?

Also, keep in mind that switching implementation will be very backwards incompatible, so stable release of it won't happen soon.

> Implement ProtobufValue for both

`ProtobufValue` is used only for the reflection implementation, and it is not needed directly by users, so it doesn't matter how it is implemented as long as everything works.

Going to look at PR now.

**Comment by stepancheg** [comment]
Implemented now.
