### ISSUE TITLE
Create dynamic message bytes from JSON encoding

### ISSUE THREAD

**Issue by autodidaddict** [stepancheg/rust-protobuf#354]
I essentially need to convert from the JSON encoded protobuf format to the raw bytes of the same message. My code doesn't need to be coupled to the messages, and I don't need/want the generated code. 

Is there a way to load the descriptor files (.desc via `protoc --descriptor_set_out`) and then use that information to read in a JSON string and get the corresponding protobuf bytes?

**Comment by stepancheg** [comment]
Implementing `DynamicMessage` (which is a concrete struct instantiated with descriptor data) is on my long todo list.

There are open questions about the design of this API.

For example, I think that `DynamicMessage` should implement `Message`. And `Message` has

```
fn descriptor(&self) -> &'static MessageDescriptor;
```

operation. Note `&'static` modifier. Since descriptor for `DynamicMessage` can be dynamically allocated, this function signature needs to be changed to

```
fn descriptor(&self) -> &MessageDescriptor;
```

It is unlikely that this will hurt a lot of people, but still.

**Comment by stepancheg** [comment]
rust-protobuf=3 support dynamic messages.
