### ISSUE TITLE
Int128 support

### ISSUE THREAD

**Issue by ilblackdragon** [stepancheg/rust-protobuf#378]
It seems that google-protobuf added int128 support recently (https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/int128.h) and given Rust has a native type - would be great to add that.

**Comment by ilblackdragon** [comment]
You are right.

For gogoproto, they made an extension with custom UInt128 type: https://godoc.org/github.com/gogo/protobuf/gogoproto

But if this is not in the standard, means that extension needs to be built in every language.

**Comment by stepancheg** [comment]
AFAIU `Uint128` in gogoproto is not even a built-in type, it is implemented as a user extension (note `test` part in type name), and these extensions are a feature of gogoproto.

Honestly, I don't know why use extensions instead of simply using `message Uint128`, so I'm not sure these custom types are needed in rust-protobuf.

And if user extensions are really needed, please open an issue for that.
