### ISSUE TITLE
Moderately-sized crate with protobuf-generated modules takes 5 minutes to compile in release mode

### ISSUE THREAD

**Issue by ancwrd1** [stepancheg/rust-protobuf#383]
I am not sure whether this issue relates to Rust compiler itself or to the generated code but the problem I experience is that the crate which contains just around 36 protobuf files of various sizes takes 5 minutes to compile in release mode, with rustc compiler memory usage maxing at 1.5Gb of RAM.
The number of files will be probably growing further so the build times will increase even more.

Considering that it takes just about 1.5-2x times as much to build the rest of the crates (more than 300 dependencies currently) there is something wrong with the generated protobuf code, either it's too complicated or too large.

**Comment by dremon** [comment]
Are all of  the generated reflection methods (descriptor methods returning or implementing `protobuf::reflect::xxx`) strictly necessary for (de)serialization? I am wondering if they can be made optional as it seems they add quite a bit to the code and perhaps compilation performance.

**Comment by stepancheg** [comment]
Reflection is also used for printing to text format (e. g. for debugging). Technically it's possible to make it optional, but I have a feeling that largest code size is occupied by unnecessary virtual functions of `Message` trait. Hint: try `nm your-binary | grep protobuf`.

Also, FYI, for primitive fields, I tried to rewrite reflection implementation to store field offsets instead of generating accessor functions. AFAIR, it did not save a lot. However, it can probably speed up compilation. I'll try to revive that patch.

**Comment by stepancheg** [comment]
Closing due to old age.
