### ISSUE TITLE
Bundle protoc binary in protoc crate

### ISSUE THREAD

**Issue by BusyJay** [stepancheg/rust-protobuf#427]
Developer may not have protoc installed, bundle binaries inside the crate can solve a common compilation error that protoc is missing.

**Comment by stepancheg** [comment]
There's `protobuf-codegen-pure` crate which doesn't require protoc binary. Doesn't it solve the issue?

**Comment by BusyJay** [comment]
It lacks of service definitions.

**Comment by stepancheg** [comment]
Why do you need service definitions?

rust-protobuf does not generate service definitions.

(And protobuf-codegen-pure can be relatively easy modified to parse service definitions).

**Comment by BusyJay** [comment]
So that it can be used to generate gRPC service definition. Otherwise protoc is still needed to parse the proto files and get a descriptor sets.

It may not be hard to support it on master, but 2.7 may require additional change including syntax parsing. 

On the other hand, bundle protoc can also do things that protobuf-codegen-pure may not do like producing descriptor set files or other commands protoc provides. It can also become a redistribution of protoc that can be reused by other crates like prost or quick-protobuf.

**Comment by stepancheg** [comment]
> protobuf-codegen-pure may not do like producing descriptor set files

Note `protobuf-codegen-pure` internally generates `FileDescriptorSet` compatible with `protoc`.

Anyway, if we don't need to update protoc command often, maybe it's OK to bundle it with `protoc` crate. And Google thankfully provides prebuilt binaries for all the platforms.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/28969/61487361-b84e8e80-a973-11e9-9f32-1dbe355d8121.png">

So PR is welcome, otherwise, I'll do it myself later.

**Comment by BusyJay** [comment]
Thanks! Some note here: not all binaries are necessary. For example, osx-x86_32 and win64 are not necessary in my opinion. Including too many binaries may make it impossible to upload to crates.io.

Actually I have a workable branch already. I will send a PR to you.

**Comment by stepancheg** [comment]
Reopened the issue, see comments in PR #430.

**Comment by benesch** [comment]
Eep, random passerby here, but please consider implementing this by vendoring the upstream google/protobuf source code and using a build script to compile protoc on the fly. It's very hard to verify that random binaries checked into source control are trustworthy. Much easier to verify source code.

Also, note that the platform detection is likely to be insufficient as is; for example the Linux binary is unlikely to work on all flavors of Linux. Alpine Linux, for example, is not a glibc-based system and the bundled binary won't work. (I guess it'll just fail to execute and you won't really be worse off, but still worth nothing.)

At the very least, please consider moving this behind a feature flag, so that downstream dependencies don't need to worry about untrusted binaries being executed inadvertently if a trusted `protoc` is not available on the PATH.

**Comment by benesch** [comment]
Just saw https://github.com/stepancheg/rust-protobuf/issues/481, which would resolve my concerns!

**Comment by stepancheg** [comment]
`protoc-bin-vendored=2.14.0` released.
