### ISSUE TITLE
How does the 2.8 branch relate to master?

### ISSUE THREAD

**Issue by nrc** [stepancheg/rust-protobuf#442]
2.8 is the latest release and was released on the 23rd July. However, GH reports there are "545 commits to master since this tag" and I can't work out what commits they are or how master and 2.8 relate to each other.

Could you let me know what is going on there? And what branch will the next version be cut from? master or something else?

Thanks!

**Comment by stepancheg** [comment]
* Master is backwards incompatible with 2.x branches (API is changed slightly but generated code changed more significantly, in particular, it adopted some ideas from other protobuf implementations in rust)
* 2.x branches are backwards compatible

All development happens in master, patches are accepted to master, and patches which do not break backward compatibility are backported to 2.x branches.

2.x+1 branch is created from 2.x branch.

* 2.x+1 version bumps usually happen for larger changes (like these which require increase of the minimum supported Rust version)
* 2.x.y+1 version bumps are done for minor barely noticeable changes or bugfixes.

So 2.9 will be created from 2.8.

3.0 version will be eventually released from master, the largest issue I want to resolve before 3.0 is large binary size due to [a large number of virtual functions in `Message` trait](https://github.com/stepancheg/rust-protobuf/issues/339), and I don't know how to solve it right.

**Comment by nrc** [comment]
Thanks for the explanation!
