### ISSUE TITLE
Can't get Option<T> directly

### ISSUE THREAD

**Issue by UltraMachine** [stepancheg/rust-protobuf#472]
I forced to do something like this:
```rust
let value: Option<_> = {
    if proto.has_value() {
        Some(proto.get_value())
    } else {
        None
    }
}
```
When wanted something like this:
```rust
let value: Option<_> = proto.get_option_value();
```

**Comment by stepancheg** [comment]
I'm hesitant to add more accessors
* because generated code size matter
* field in proto2 may have default values, `get_value` returns the default value (not just zero) when the value is not set
* generally, people tend to switch to `syntax = "proto3"` nowadays (see below)

Also, backward compatibility is an issue.

If you have specific suggestions, go ahead, otherwise, I can suggest:
* use `syntax = "proto3"`, it makes all fields public
* use `expose_fields` codegen option which makes fields public even when `syntax = "proto2"`
