### ISSUE TITLE
rustfmt ignore deprecated

### ISSUE THREAD

**Issue by austinabell** [stepancheg/rust-protobuf#493]
Now in Rust 1.44, the 

```
#![cfg_attr(rustfmt, rustfmt_skip)]
```

tags are now deprecated in favour of `#![rustfmt::skip]`, I tried to replace the tags but for some reason it doesn't work with the autogen code, and I didn't dig deeper.

To replicate, I think it's just sufficient when updating to 1.44 and run a cargo fmt and it will format all autogen files in this repo or otherwise.

**Comment by Elrendio** [comment]
See https://github.com/rust-lang/rust/issues/73078 to see why `#![rustfmt::skip]` doesn't work. 

In short: it's a bug in rustfmt, should be fixed asap. I think it's best to migrate to `#![rustfmt::skip]` and wait for rustfmt to fix their bug rather than add `#[rustfmt::skip]` on all items on the generated code.

**Comment by hds** [comment]
The change in PR #495 breaks compilation of protobuf 2.15 (at least for me). I know the error is in rustfmt, but until it's fixed, perhaps a more conservative approach could be taken?

The PR mentions that this issue should be fixed in 1.44.1, but so far I see the same behaviour adding the two macros to the default example in the Rust playground:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=392753339f4652381c92297a5831c8a4

**Comment by stepancheg** [comment]
@hds can you please provide full example, which does not work?

AFAIU, 

```
#![allow(unused_attributes)]
#![rustfmt::skip] 
```

does not work in root module, but works fine in other modules.

**Comment by stepancheg** [comment]
Just in case, this file is [committed to the repostory](https://github.com/stepancheg/rust-protobuf/blob/v2.15/protobuf/src/descriptor.rs#L9), it compiles just fine.

**Comment by stepancheg** [comment]
... it is [tested with Rust 1.44.1](https://github.com/stepancheg/rust-protobuf/blob/95d47d445f707d40bd4a08b4e89274a35b0b1761/.travis.yml#L9).

**Comment by dvc94ch** [comment]
Same here, it works locally, but breaks ci build. Very strange

**Comment by stepancheg** [comment]
@dvc94ch your logs say all jobs install rust nightly-2020-02-05, which is quite old.

**Comment by stepancheg** [comment]
... even stable jobs seems to install the same nightly.

**Comment by stepancheg** [comment]
Yep,
<img width="343" alt="Screenshot 2020-06-30 at 02 07 11" src="https://user-images.githubusercontent.com/28969/86071190-9233d880-ba76-11ea-9db2-a54a36ccd27b.png">

**Comment by dvc94ch** [comment]
Thanks, that was indeed the problem

**Comment by Xaeroxe** [comment]
Protobuf 2.15 isn't compiling for rust 1.43 oddly. Protobuf 2.14 does compile using the same compiler.

**Comment by stepancheg** [comment]
@Xaeroxe it is compatible with Rust 1.44.1.

Unfortunately rust-protobuf dependencies on rustfmt macros and clippy make it very hard to make library compatible with a wide range of rust compiler.

Life would be much easier if rustfmt supported comment markers, not just rust attributes. And `@generated` sounds like a great option to me. Add a like to this issue: https://github.com/rust-lang/rustfmt/issues/3958.

**Comment by hds** [comment]
> @hds can you please provide full example, which does not work?
> 
> AFAIU,
> 
> ```
> #![allow(unused_attributes)]
> #![rustfmt::skip] 
> ```
> 
> does not work in root module, but works fine in other modules.

I retested locally ensuring 1.44.1 and you are right, it does compile fine outside of the root module.
