### ISSUE TITLE
Carefully work with integer overflow in serialization and deserialization

### ISSUE THREAD

**Issue by BusyJay** [stepancheg/rust-protobuf#530]
When I try to serialize a long string (>4G), the library will panic with strange error:
```
thread 'main' panicked at 'refresh_buffer must not be called on CodedOutputStream create from slice', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1038:17
stack backtrace:
   0: std::panicking::begin_panic
             at /home/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: protobuf::stream::CodedOutputStream::refresh_buffer
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1038
   2: protobuf::stream::CodedOutputStream::write_raw_bytes
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1075
   3: protobuf::stream::CodedOutputStream::write_raw_varint32
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1122
   4: protobuf::stream::CodedOutputStream::write_bytes_no_tag
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1372
   5: protobuf::stream::CodedOutputStream::write_string_no_tag
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1379
   6: protobuf::stream::CodedOutputStream::write_string
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/stream.rs:1397
   7: <grpcio_proto::example::helloworld::HelloRequest as protobuf::message::Message>::write_to_with_cached_sizes
```

Perhaps it should return error.

**Comment by BusyJay** [comment]
It may be related to overflow issue in `compute_size`. My usage is
```
let len = msg.compute_size();
let mut bytes = [0; len as usize];
let mut s = CodedOutputStream::bytes(&mut bytes);
msg.write_to_with_cached_sizes(&mut s)
```
The long string exceeds u32 and result in an overflowed value `len`.

**Comment by stepancheg** [comment]
This is a bug, and it's not easy to fix it without breaking backwards compatibility: `Message::compute_size` returns `u32`: not `u64`, and not `Result`.

This need be fixed in rust-protobuf 3, which will backwards-incompatible.

Note that
* inner messages cannot exceed 4G; encoding allows it, but IIRC other implementations don't
* grpc messages cannot exceed 4G: grpc message size is encoded as u32
* Google protobuf authors recommend limiting protobuf message to something like 100M

If you have suggestions how to better fix it in rust-protobuf 2, please let me know.

**Comment by BusyJay** [comment]
How about adding a new API that can return `usize` or `Result<u32>`?

**Comment by stepancheg** [comment]
OK, so it will be

```
trait Message {
  // this is implemented by old generated code
  #[deprecated]
  fn compute_size(&self) -> u32 {
    self.compute_size_new().unwrap()
  }

  // this is implemented by new generated code
  // what would be a good method name?
  fn compute_size_new(&self) -> Result<u32> {
    Ok(self.compute_size())
  }
}
```

It will result in further slight increase of binary size (since all `Message` functions are virtual in rust-protobuf 2), but that's acceptable.

I would pick `Result<u32>` over `usize` because `usize` can be exceeded when `bytes` feature is used, and the same large `Bytes` object is stored in multiple fields.

**Comment by BusyJay** [comment]
I'm not a good at naming, but overall LGTM. 👍

**Comment by BusyJay** [comment]
By the way, returning `Result` means to check boundary at every calculation, which may have big performance impact.

**Comment by stepancheg** [comment]
Performance of returning `Result` should be measured, yes, thanks. Alternatively, the `compute_size_new` function may return `u64`, and overflow can be checked only once before the serialisation.

**Comment by BusyJay** [comment]
How about making it not panic if `refresh_buffer` is called first? Returns error should also be a sufficient fix.

**Comment by stepancheg** [comment]
Fixed in version 3.
