### ISSUE TITLE
protobuf 2.22.0 fails to compile

### ISSUE THREAD

**Issue by mgild** [stepancheg/rust-protobuf#547]
rustc 1.40.0 (73528e339 2019-12-16)
```
error[E0658]: non-builtin inner attributes are unstable
 --> /Users/mgild/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.22.0/src/descriptor.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable
```

**Comment by mgild** [comment]
Build command `cargo build-bpf --manifest-path=./programs/helloworld/Cargo.toml --bpf-out-dir=dist/program`

**Comment by stepancheg** [comment]
Minimum supported version of rustc is 1.44.1 [since release 2.15](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#2150---2020-06-21).

If there's a reason to support older version of rustc we can think of how to make rust-protobuf support older versions. I have not found an easy way.
