### ISSUE TITLE
How to include generated file written under OUT_DIR

### ISSUE THREAD

**Issue by egrimley-arm** [stepancheg/rust-protobuf#673]
Recent versions of `protobuf-codegen` seem to enable putting the generated `.rs` file under `OUT_DIR` (using `cargo_out_dir`), but it's unclear to me how to use the `.rs` file when it's under `OUT_DIR`. It does not seem to be possible to `include!` the file because of:

1. the inner attributes (`#!allow(...)`, etc.): see https://github.com/rust-lang/rfcs/issues/752

2. the documentation comment (`//! Generated file from` ...)

Sorry if this is in the documentation somewhere and I've missed it or if I'm just using the wrong combination of versions.

**Comment by matejcik** [comment]
faced the same problem. The solution seems to be to create your own `mod.rs` whose contents are:
```rust
include!(concat!(env!("OUT_DIR"), "/mod.rs"));
```
(this requires [gen_mod_rs](https://docs.rs/protobuf-codegen/latest/protobuf_codegen/struct.Customize.html#method.gen_mod_rs) to be enabled, which is the default since version 3)

Rust somehow magically picks the rest of the modules from the outdir.

related original issues:
https://github.com/stepancheg/rust-protobuf/issues/117
https://github.com/stepancheg/rust-protobuf/pull/523
https://github.com/stepancheg/rust-protobuf/pull/525

**Comment by egrimley-arm** [comment]
Thank you, @matejcik . That's very helpful. I also found this useful example: https://github.com/jgarzik/rust-protobuf-example

However, there's one thing I don't understand yet: how `cargo` dependencies are tracked. With that `rust-protobuf-example` I found that any change to any file (even `rust-protobuf-example/newdir/newfile`, for example) results in a rebuild. But when I had a crate that was a dependency of a larger project I found I had to add my own `println!("cargo:rerun-if-changed=...")`:
https://github.com/veracruz-project/veracruz/blob/870db97945f9880cdbc8d3c4002fda64f2bb969d/transport-protocol/build.rs#L13-L15

But that's a different issue. I'll close this one.
